### ISSUE TITLE
LTS使用时遇到的问题

### ISSUE THREAD

**Issue by 15692109791** [qq254963746/light-task-scheduler#74]
我在使用LTS的过程中遇到了这样一个问题，JobClient使用testProtector的运行方式，定时产生任务数据。但是在每次定时执行时，系统的线程数就会增大，并且累加。最后线程数超过系统最大值，就报出OutOfMemoryError错误。看起来像是线程泄漏，但是也没有找到出现问题的原因。
以下是我的JobClient代码：
![2](https://cloud.githubusercontent.com/assets/13942521/9437690/a5f9ff86-4a8a-11e5-8157-026482f0b5ae.jpg)
![3](https://cloud.githubusercontent.com/assets/13942521/9437704/c48ee6b4-4a8a-11e5-87f2-396df5179158.jpg)
![4](https://cloud.githubusercontent.com/assets/13942521/9437717/ef132a30-4a8a-11e5-95a0-d5a3bdbb5200.jpg)

以下是JobClient报出的错误信息：
![p1](https://cloud.githubusercontent.com/assets/13942521/9437803/9f637a52-4a8b-11e5-817a-356891e56d30.jpg)

**Comment by qq254963746** [comment]
首先，你这个用法就有点不对，1. 一般一个JVM保证有一个JobClient就够了，多了就非常浪费资源了，2. 你线程达到了系统的最大线程数，必然程序会出现问题，提示已经很明显了： unable to create native thread
